services:
  backend:
    build: 
      context: ./backend
    container_name: backend-govbride
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules

  frontend:
    build: 
      context: ./frontend
    container_name: frontend-govbride
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
